server:
  port: 8085

## This is important if you'll use FeignClient
client-services-urls:
  gateway-service: ${GATEWAY_SERVICE_URL}
  order-service: http://localhost:8080

authService:
  jwtTokenSecret: ${JWT_TOKEN_SECRET}

management:
  observations:
    key-values:
      application: ${spring.application.name}
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  application:
    name: Notification Service
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: localhost:5672
    username: rabbit
    password: rabbit
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full


eventArchitecture:
  ecommerceEventExchange: ecommerce_event_topic
  notificationOnPaymentStatusChangeQueue: notification_on_payment_status_change_queue
  notificationOnOrderStatusChangeQueue: notification_on_order_status_change_queue

