server:
  port: 8085

authService:
  jwtTokenSecret: RW50ZXIgdGhlIG1hdHJpeC4gSXQncyBhIGZhY2VzaXRpbmcgd29ybGQgb3V0IHRoZXIh

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db
    username: notification_user
    password: s3cr3t_notification
    driver-class-name: com.mysql.cj.jdbc.Driver
