server:
  port: 8082

authService:
  jwtTokenSecret: RW50ZXIgdGhlIG1hdHJpeC4gSXQncyBhIGZhY2VzaXRpbmcgd29ybGQgb3V0IHRoZXIh

management:
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: "health,info,prometheus"
  observations:
    key-values:
      application: ${spring.application.name}

spring:
  application:
    name: Catalog Service
