server:
  port: 8080

authService:
  jwtTokenSecret: RW50ZXIgdGhlIG1hdHJpeC4gSXQncyBhIGZhY2VzaXRpbmcgd29ybGQgb3V0IHRoZXIh

client-services-urls:
  payment-service: http://localhost:8084

management:
  observations:
    key-values:
      application: ${spring.application.name}
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: 'health,info,prometheus'

spring:
  application:
    name: Orders Service
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: localhost:5672
    username: rabbit
    password: rabbit

logging:
  level:
    br.com.jlcorradi: TRACE

eventArchitecture:
  ecommerceEventExchange: ecommerce_event_topic
