server:
  port: 8080

authService:
  jwtTokenSecret: RW50ZXIgdGhlIG1hdHJpeC4gSXQncyBhIGZhY2VzaXRpbmcgd29ybGQgb3V0IHRoZXIh

client-services-urls:
  payment-service: http://localhost:8084

management:
  observations:
    key-values:
      application: ${spring.application.name}
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: 'health,info,prometheus'
metrics:
  tags:
    application: ${spring.application.name}

spring:
  application:
    name: Orders Service
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: ecommerce
    password: s3cr3t
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    br.com.jlcorradi: TRACE
