server:
  port: 8090

client-services-urls:
  orders-service: http://localhost:8080
  auth-service: http://localhost:8081
  payment-service: http://localhost:8082

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    metrics:
      enabled: true

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Host

      routes:
        - id: forward-orders
          uri: ${client-services-urls.orders-service}
          predicates:
            - Path=/orders-service/**
          filters:
            - RewritePath=/orders-service/(?<segment>.*), /$\{segment}
            - AuthFilter

        - id: forward-users
          uri: ${client-services-urls.auth-service}
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}

        - id: forward-payment
          uri: ${client-services-urls.payment-service}
          predicates:
            - Path=/payment-service/**
          filters:
            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}
            - AuthFilter