version: '3.3'
services:
  prometheus:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    image: 'prom/prometheus:v2.14.0'
    ports:
      - '9090:9090'
    command: '--config.file=/etc/prometheus/config/prometheus.yml'
    volumes:
      - './config/:/etc/prometheus/config'

  grafana:
    image: 'grafana/grafana:6.5.0'
    ports:
      - '3000:3000'