global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'OrdersServiceApplication'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]

  - job_name: 'GatewayServiceApplication'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8090' ]

  - job_name: 'NotificationServiceApplication'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8085' ]

  - job_name: 'CatalogServiceApplication'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]

  - job_name: 'PaymentServiceApplication'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8084' ]

  - job_name: 'InventoryServiceApplication'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]

  - job_name: 'AuthServiceApplication'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]


#remote_write:
#  - url: '<Your Prometheus remote_write endpoint>'
#    basic_auth:
#      username: '<Your Grafana Username>'
#      password: '<Your Grafana API key>'