server:
  port: 8086

authService:
  jwtTokenSecret: RW50ZXIgdGhlIG1hdHJpeC4gSXQncyBhIGZhY2VzaXRpbmcgd29ybGQgb3V0IHRoZXIh

management:
  observations:
    key-values:
      application: ${spring.application.name}
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  application:
    name: InvoiceServiceApplication
  rabbitmq:
    addresses: localhost:5672
    username: rabbit
    password: rabbit


eventArchitecture:
  ecommerceEventExchange: ecommerce_event_topic
