server:
  port: ${SERVICE_PORT}

## This is important if you'll use FeignClient
client-services-urls:
  gateway-service: ${GATEWAY_SERVICE_URL}


authService:
  jwtTokenSecret: ${JWT_TOKEN_SECRET}

management:
  observations:
    key-values:
      application: ${spring.application.name}
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  application:
    name: Application Name
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver