authService:
  jwtTokenSecret: RW50ZXIgdGhlIG1hdHJpeC4gSXQncyBhIGZhY2VzaXRpbmcgd29ybGQgb3V0IHRoZXIh

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory
    username: inventory_user
    password: s3cr3t
